package net

import (
	"os"
	"strings"
)

type DNS struct {
	Nameserver []string
	Search     []string
	Options    []string
	Domain     string
}

func (dns DNS) write(destFile string) error {
	rc := ""

	for _, ns := range dns.Nameserver {
		rc += "nameserver " + ns + "\n"
	}

	for _, s := range dns.Search {
		rc += "search " + s + "\n"
	}

	if dns.Domain != "" {
		rc += "domain " + dns.Domain + "\n"
	}

	if len(dns.Options) > 0 {
		rc += "options " + strings.Join(dns.Options, " ") + "\n"
	}

	if rc != "" {
		rc = "# Generated by " + os.Args[0] + "\n" + rc
		return writeFile(destFile, rc)
	}
	return nil
}
